apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing
  namespace: zebraflights
  labels:
    app: data-preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
        - name: data-preprocessing
          image: preprocess:latest
          imagePullPolicy: IfNotPresent #use local image if available
          ports:
            - containerPort: 8000
          env:
            - name: DATA_DIR
              value: /data
            - name: PORT
              value: "8000"
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc

