apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zebraflights-ingress
  namespace: zebraflights
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: zebraflights.local  # You can use localhost if no DNS
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui-service
                port:
                  number: 80