apiVersion: v1
kind: Service
metadata:
  name: model-inference
  labels:
    app: model-inference
spec:
  type: ClusterIP
  selector:
    app: model-inference
  ports:
    - name: http
      port: 80
      targetPort: 5002
      protocol: TCP
