apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
  namespace: zebraflights
  labels:
    app: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
        - name: model-training
          image: training:latest
          imagePullPolicy: IfNotPresent  
          ports:
            - containerPort: 8000
          env:
            - name: ENCODED_DIR
              value: /data/02_preprocessed
            - name: MODEL_DIR
              value: /data/04_model_output
            - name: PORT
              value: "8000"
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc

