apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ui:latest  # <- replace with your actual image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: MODEL_ENDPOINT
              value: "http://model-inference-service:5002/predict"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
